//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("five_ways_to_wellbeing_web.Resources.Strings-GB", typeof(Strings_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string button_add_activity {
            get {
                return ResourceManager.GetString("button_add_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days logged.
        /// </summary>
        public static string days_active {
            get {
                return ResourceManager.GetString("days_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is how your day is looking so far.
        /// </summary>
        public static string description_today {
            get {
                return ResourceManager.GetString("description_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five ways to wellbeing.
        /// </summary>
        public static string five_ways_to_wellbeing {
            get {
                return ResourceManager.GetString("five_ways_to_wellbeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The five ways to wellbeing provide areas of focus that help you maintain positive mental wellbeing. Think of it as your five a day for your mental wellbeing!.
        /// </summary>
        public static string five_ways_to_wellbeing_description {
            get {
                return ResourceManager.GetString("five_ways_to_wellbeing_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string title_progress {
            get {
                return ResourceManager.GetString("title_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string title_today {
            get {
                return ResourceManager.GetString("title_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be active.
        /// </summary>
        public static string wellbeing_be_active {
            get {
                return ResourceManager.GetString("wellbeing_be_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be active is all about getting in some exercise, whether that be grabbing your yoga mat and taking on the downward dog, going for a short walk during your lunch break or training for your next marathon, make sure to keep it at a level you are comfortable with, if you don&apos;t feel better, change it up until you find something you love..
        /// </summary>
        public static string wellbeing_be_active_description {
            get {
                return ResourceManager.GetString("wellbeing_be_active_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string wellbeing_connect {
            get {
                return ResourceManager.GetString("wellbeing_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect is all about building relationships, in person or over video call it all counts, what really matters is that you spend time getting to know each other deeply, build a sense of trust, go deeper than the superficial, and most importantly make time to listen..
        /// </summary>
        public static string wellbeing_connect_description {
            get {
                return ResourceManager.GetString("wellbeing_connect_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        public static string wellbeing_give {
            get {
                return ResourceManager.GetString("wellbeing_give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving is all about using what you have to benefit someone else. Whether that be giving a smile or a quick nod of the head to a stranger as you pass by or donning the apron for a charity bake sale, it all counts..
        /// </summary>
        public static string wellbeing_give_description {
            get {
                return ResourceManager.GetString("wellbeing_give_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep learning.
        /// </summary>
        public static string wellbeing_keep_learning {
            get {
                return ResourceManager.GetString("wellbeing_keep_learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep learning is all about taking time to learn what you love. Growing your skills and finding a real sense of achievement in what you love to do. Whether it be a new skill or String Theory, get out there and start learning..
        /// </summary>
        public static string wellbeing_keep_learning_description {
            get {
                return ResourceManager.GetString("wellbeing_keep_learning_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take notice.
        /// </summary>
        public static string wellbeing_take_notice {
            get {
                return ResourceManager.GetString("wellbeing_take_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take notice is all about taking the time to reflect, look at the bigger picture, how was your day today? Make the most of the little things, put that phone down, stop scrolling. Ah, that&apos;s better, now you can enjoy the moment..
        /// </summary>
        public static string wellbeing_take_notice_description {
            get {
                return ResourceManager.GetString("wellbeing_take_notice_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string wellbeing_unassigned {
            get {
                return ResourceManager.GetString("wellbeing_unassigned", resourceCulture);
            }
        }
    }
}
